version: '3.9'
services:

  storage:
    container_name: task-streaming-storage
    image: mongo:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - task_streaming_storage_v:/data/db
    networks:
      - worknet

  webapp:
    container_name: task-streaming-webapp
    depends_on:
      - storage
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=storage
      - DB_NAME=task-streaming-storage
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/webapp
      - task_streaming_webapp_node_modules:/node_modules
    networks:
      - worknet
    command: ["node", "dist/main.js"]

volumes:
  task_streaming_storage_v:
  task_streaming_webapp_node_modules:

networks:
  worknet:
